import type { Plugin } from '@terrazzo/parser';
import { tokenToColor } from '@terrazzo/token-tools';
import { to as convert } from 'colorjs.io/fn';

/* oxlint-disable require-await */

export const FORMAT = 'android';

const PLUGIN_NAME = '@terrazzo/plugin-android';

export interface AndroidPluginOptions {
  /**
   * Kotlin package for the generated file (e.g. "com.example.tokens"). Omitted from the file if not set.
   */
  packageName?: string;
  /**
   * Name of the generated interface, and the prefix of its light and dark objects. Also the filename.
   * @default "Tokens"
   */
  objectName?: string;
}

/** Kotlin hard keywords, which can’t be used as a property name without backticks */
const KOTLIN_KEYWORDS = new Set([
  'as',
  'break',
  'class',
  'continue',
  'do',
  'else',
  'false',
  'for',
  'fun',
  'if',
  'in',
  'interface',
  'is',
  'null',
  'object',
  'package',
  'return',
  'super',
  'this',
  'throw',
  'true',
  'try',
  'typealias',
  'typeof',
  'val',
  'var',
  'when',
  'while',
]);

export default function PluginAndroid({
  packageName,
  objectName = 'Tokens',
}: AndroidPluginOptions = {}): Plugin {
  return {
    name: PLUGIN_NAME,
    async transform({ tokens, setTransform }) {
      for (const [id, token] of Object.entries(tokens)) {
        switch (token.$type) {
          case 'color': {
            for (const [mode, modeValue] of Object.entries(token.mode)) {
              if (!modeValue) {
                continue;
              }
              const parsed = tokenToColor(modeValue.$value);
              const {
                coords: [red, green, blue],
                alpha,
              } = convert(parsed, 'p3', { inGamut: true });
              setTransform(id, {
                format: FORMAT,
                mode,
                value: `Color(${[red, green, blue, alpha].map(toFloat).join(', ')}, ColorSpaces.DisplayP3)`,
                meta: { 'token-listing': { name: `${objectName}.${toPropertyName(token.id)}` } },
              });
            }
            break;
          }

          // TODO: other types
        }
      }
    },
    async build({ context, getTransforms, outputFile }) {
      const colors = getTransforms({ id: '*', format: FORMAT, mode: '.' }).toSorted((a, b) =>
        a.token.id.localeCompare(b.token.id, 'en', { numeric: true }),
      );
      if (colors.length === 0) {
        return;
      }

      const seen = new Map<string, string>();
      const members: {
        name: string;
        description?: string;
        light: string;
        dark: string | undefined;
      }[] = [];
      for (const token of colors) {
        const name = toPropertyName(token.token.id);
        const existing = seen.get(name);
        if (existing) {
          context.logger.error({
            group: 'plugin',
            label: PLUGIN_NAME,
            message: `Tokens ${existing} and ${token.token.id} both map to the Kotlin property ${name}`,
          });
        }
        seen.set(name, token.token.id);
        const [darkToken] = getTransforms({ id: token.token.id, format: FORMAT, mode: 'dark' });
        members.push({
          name,
          description: token.token.$description,
          light: token.value as string,
          dark: darkToken?.value as string | undefined,
        });
      }
      const hasDark = members.some((m) => m.dark !== undefined);

      const lines: string[] = ['// This file was generated by Terrazzo. Do not edit.', ''];
      if (packageName) {
        lines.push(`package ${packageName}`, '');
      }
      lines.push(
        'import androidx.compose.ui.graphics.Color',
        'import androidx.compose.ui.graphics.colorspace.ColorSpaces',
        '',
        `interface ${objectName} {`,
      );
      for (const { name, description } of members) {
        if (description) {
          lines.push(
            `  /** ${description.replaceAll('*/', '* /').replaceAll(/\s*\n\s*/g, ' ')} */`,
          );
        }
        lines.push(`  val ${name}: Color`);
      }
      lines.push('}', '', `object ${objectName}Light : ${objectName} {`);
      for (const { name, light } of members) {
        lines.push(`  override val ${name} = ${light}`);
      }
      lines.push('}');
      if (hasDark) {
        lines.push('', `object ${objectName}Dark : ${objectName} {`);
        for (const { name, light, dark } of members) {
          lines.push(`  override val ${name} = ${dark ?? light}`);
        }
        lines.push('}');
      }

      outputFile(`${objectName}.kt`, `${lines.join('\n')}\n`);
    },
  };
}

/** Token ID → camelCase Kotlin property name (color.primitive.blue.1 → colorPrimitiveBlue1) */
export function toPropertyName(id: string): string {
  const words = id.split(/[^A-Za-z0-9]+/).filter(Boolean);
  let name = words
    .map((word, i) =>
      i === 0
        ? word.charAt(0).toLowerCase() + word.slice(1)
        : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join('');
  if (/^[0-9]/.test(name)) {
    name = `_${name}`;
  }
  return KOTLIN_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

/** Kotlin Float literal, rounded to what a Float can hold (0.984313725 → 0.984314f, 1 → 1f) */
function toFloat(v: unknown): string {
  const n = typeof v === 'number' && Number.isFinite(v) ? v : 0;
  return `${Number(n.toFixed(6))}f`;
}
