// This file was generated by Terrazzo. Do not edit.

package com.example.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces

interface Want {
  val colorPrimitiveBlue1: Color
  val colorPrimitiveBlue2: Color
  val colorPrimitiveBlue3: Color
  val colorPrimitiveBlue4: Color
  val colorPrimitiveBlue5: Color
  val colorPrimitiveBlue6: Color
  val colorPrimitiveBlue7: Color
  val colorPrimitiveBlue8: Color
  val colorPrimitiveBlue9: Color
  val colorPrimitiveBlue10: Color
  val colorPrimitiveBlue11: Color
  val colorPrimitiveBlue12: Color
  /** Brand green, outside sRGB */
  val colorSemanticBrand: Color
  val colorSemanticLink: Color
  val colorSemanticOverlay: Color
}

object WantLight : Want {
  override val colorPrimitiveBlue1 = Color(0.985712f, 0.991898f, 0.999169f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue2 = Color(0.961096f, 0.979623f, 0.99788f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue3 = Color(0.912028f, 0.955107f, 0.991793f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue4 = Color(0.854576f, 0.934103f, 0.993101f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue5 = Color(0.787471f, 0.893921f, 0.989581f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue6 = Color(0.709208f, 0.842059f, 0.974561f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue7 = Color(0.605511f, 0.77811f, 0.947903f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue8 = Color(0.449347f, 0.686338f, 0.916108f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue9 = Color(0.246572f, 0.55605f, 0.968903f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue10 = Color(0.234683f, 0.525167f, 0.91194f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue11 = Color(0.203849f, 0.447946f, 0.782562f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue12 = Color(0.1016f, 0.193193f, 0.37872f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticBrand = Color(0.1f, 0.8f, 0.3f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticLink = Color(0.246572f, 0.55605f, 0.968903f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticOverlay = Color(0f, 0f, 0f, 0.5f, ColorSpaces.DisplayP3)
}

object WantDark : Want {
  override val colorPrimitiveBlue1 = Color(0.057468f, 0.081469f, 0.121896f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue2 = Color(0.07304f, 0.097139f, 0.148538f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue3 = Color(0.07908f, 0.154469f, 0.269367f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue4 = Color(0.069092f, 0.196438f, 0.371256f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue5 = Color(0.093901f, 0.246707f, 0.440107f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue6 = Color(0.140225f, 0.297326f, 0.512782f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue7 = Color(0.194156f, 0.359624f, 0.600809f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue8 = Color(0.238038f, 0.433225f, 0.718943f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue9 = Color(0.246572f, 0.55605f, 0.968903f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue10 = Color(0.343532f, 0.611401f, 0.971332f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue11 = Color(0.50464f, 0.714413f, 0.97678f, 1f, ColorSpaces.DisplayP3)
  override val colorPrimitiveBlue12 = Color(0.788301f, 0.897736f, 0.989831f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticBrand = Color(0.1f, 0.8f, 0.3f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticLink = Color(0.246572f, 0.55605f, 0.968903f, 1f, ColorSpaces.DisplayP3)
  override val colorSemanticOverlay = Color(0f, 0f, 0f, 0.7f, ColorSpaces.DisplayP3)
}
