// This file was generated by Terrazzo. Do not edit.

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces

interface Want {
  val colorSurface: Color
  val colorText: Color
}

object WantLight : Want {
  override val colorSurface = Color(1f, 1f, 1f, 1f, ColorSpaces.DisplayP3)
  override val colorText = Color(0.1f, 0.1f, 0.1f, 1f, ColorSpaces.DisplayP3)
}
